# Generated by Django 4.2 on 2023-04-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=80)),
                ('marca', models.CharField(max_length=80)),
                ('precio', models.IntegerField()),
                ('año_fabricacion', models.IntegerField()),
            ],
        ),
    ]
